version: '3.5'
services:
    redis-1:
        image: redis:6.0.6
        hostname: redis-1
        container_name: redis-1
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 10001:6379
        volumes:
            - /tmp/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            redis-net:
                ipv4_address: 172.20.0.101

    redis-2:
        image: redis:6.0.6
        hostname: redis-2
        container_name: redis-2
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 10002:6379
        volumes:
            - /tmp/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            redis-net:
                ipv4_address: 172.20.0.102

    redis-3:
        image: redis:6.0.6
        hostname: redis-3
        container_name: redis-3
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 10003:6379
        volumes:
            - /tmp/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            redis-net:
                ipv4_address: 172.20.0.103

    redis-4:
        image: redis:6.0.6
        hostname: redis-4
        container_name: redis-4
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 10004:6379
        volumes:
            - /tmp/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            redis-net:
                ipv4_address: 172.20.0.104
    
    redis-5:
        image: redis:6.0.6
        hostname: redis-5
        container_name: redis-5
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 10005:6379
        volumes:
            - /tmp/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            redis-net:
                ipv4_address: 172.20.0.105

    redis-6:
        image: redis:6.0.6
        hostname: redis-6
        container_name: redis-6
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - 10006:6379
        volumes:
            - /tmp/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            redis-net:
                ipv4_address: 172.20.0.106

networks:
    redis-net:
        name: redis-net
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/24
