version: '3.5'

services:
  pulsar:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  manager:
    image: apachepulsar/pulsar-manager:v0.2.0
    environment:
      SPRING_CONFIGURATION_FILE : /pulsar-manager/pulsar-manager/application.properties
    ports:
      - "9527:9527"
      - "7750:7750"
