apiVersion: v1
kind: Service
metadata:
    name: "monolith"
spec:
    selector:
        app: "monolith"
    ports:
        - protocol: "TCP"
          port: 80
          targetPort: 80
          nodePort: 31000
    type: NodePort
