version: '3'
services:
    etcd-1:
        image: quay.io/coreos/etcd:v3.4.9
        hostname: etcd-1
        container_name: etcd-1
        command: etcd --data-dir=data.etcd --name etcd-1 --initial-advertise-peer-urls http://etcd-1:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://etcd-1:2379 --listen-client-urls http://0.0.0.0:2379 --initial-cluster etcd-1=http://etcd-1:2380 --initial-cluster-state new --initial-cluster-token etcd-token-01 --snapshot-count 100
        ports:
            - 2379:2379
        networks:
            - etcd-net
networks:
    etcd-net:
